### ISSUE TITLE
OCP 3.9 Using secrets to hide parameters doesnt check in namespace 'aws-service-broker'

### ISSUE THREAD

**Issue by VeerMuchandi** [awslabs/aws-servicebroker-documentation#12]
Created secret 'aws-secret' in 'was-service-broker' namespace. 

But there is a warning in logs as below
[WARNING] - Unable to load secret 'aws-secret' from namespace ''

and the values for aws_access_key and aws_secret_key are not taken from the secret.

**Comment by dymurray** [comment]
This is because the configmap being used does not set `openshift.namespace` to `aws-service-broker`.

The template is referenced here: https://github.com/awslabs/aws-servicebroker-documentation/blob/master/getting-started.md#production but also all throughout that documentation page. The secrets filtering will not work unless this value is set.

**Comment by VeerMuchandi** [comment]
Thanks @dymurray 

Added the following to broker-config in the was-service-broker namespace

`openshift:
      namespace: aws-service-broker`
and

` oc rollout latest aws-asb`

That fixed the issue!!
